--liquibase formatted sql

--changeset burgasvv:1
create table if not exists card
(
    id          uuid                    default gen_random_uuid() unique not null,
    account_id  uuid unique references account (id) on delete cascade on update cascade,
    number      varchar unique not null,
    code        bigint generated by default as identity unique,
    valid_until date           not null,
    balance     decimal        not null default 0 check ( balance >= 0 ),
    pin         varchar        not null,
    created_at  timestamp      not null default now()
)