
server:
  port: 9000
spring:
  application:
    name: bank-spring
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5000/bank_spring_db"
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  liquibase:
    driver-class-name: org.postgresql.Driver
    password: postgres
    user: postgres
    url: "jdbc:postgresql://localhost:5000/bank_spring_db"
  data:
    redis:
      host: localhost
      port: 6000
logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction.interceptor: TRACE